name: pilisp_web
description: Extension of PiLisp targeting the Web (JavaScript)
version: 1.0.0
repository: https://github.com/pilisp/pilisp-web

environment:
  sdk: '>=2.19.1 <3.0.0'

# dependencies:
#   path: ^1.8.0

dependencies: 
  pilisp: ^1.0.0-alpha.7

dev_dependencies:
  build_runner: ^2.3.3
  build_web_compilers: ^4.0.3
  lints: ^2.0.0

dependency_overrides:
  pilisp:
    path: ../pilisp-core
