#!/usr/bin/env bash

set -eu

"$(dirname "$0")"/setup

if $PILISP_LOCAL_DEV ; then source "$(dirname "$0")/../../.docs-env/bin/activate" ; fi

mkdocs serve # --dirtyreload # If the build becomes too slow, use this.
