#!/usr/bin/env bash

set -eu

echo '[1/3] Running dart pub get for pilisp-core...'
(cd pkgs/pilisp-core && dart pub get )

echo ''
echo '[2/3] Running dart pub get for pilisp-cli...'
(cd pkgs/pilisp-cli && dart pub get )

echo ''
echo '[3/3] Running dart pub get for pilisp-native...'
(cd pkgs/pilisp-native && dart pub get )
