#!/usr/bin/env bash

set -eu

echo '[1/3] Testing pilisp-core...'
( cd pkgs/pilisp-core && ./script/test )

echo ''
echo '[2/3] Testing pilisp-cli...'
( cd pkgs/pilisp-cli && ./script/test )

echo ''
echo '[3/3] Testing pilisp-native...'
( cd pkgs/pilisp-native && ./script/test )
